### PR TITLE
Issue #14: PHP 8 compatibility

### PR DESCRIPTION
**Pull request by stijndmd**
https://github.com/cultuurnet/culturefeed_d8/issues/14

### CODE REVIEW

**Comment by zuuperman** [comment]
Is your calendar summary still working? In the organizer branch (https://github.com/cultuurnet/culturefeed_d8/tree/epic/organizers), we had to go back to v2 (that is marked as php 8 compatible). We are running that version on a php 8 server without any issues.

**Comment by stijndmd** [comment]
Not sure, still trying to get it set up using composer.

The organizers branch requires cultuurnet/search-v3 dev-epic/organizers which in turn requires php 7.1. How do I get past that then?

**Comment by stijndmd** [comment]
https://github.com/cultuurnet/search-v3/issues/64

apparently https://github.com/cultuurnet/culturefeed_d8/pull/17#issuecomment-1549294193 has wrong info and this doesn't work for php8

**Comment by zuuperman** [comment]
The 10.x branch has now php 8 support

**Pull request closed without merging**
